name: exampleGraphx
description: Graphx rendering prototype examples

publish_to: "none"

version: 1.0.0+21

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_icons: ^1.1.0
  flutter_svg: 0.18.1
  graphx:
    path: ../
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/fb_reactions/
    - assets/bookmark_button/
    - assets/card_rotation/
    - assets/xmas/
    - assets/murat_coffee/
    - assets/run_hero/
    - assets/run_hero/parallax/
    - assets/heart_reaction/
    - assets/pizza_box/
    - assets/isma_chart/
    - assets/trigrid/

  fonts:
    - family: pressstart
      fonts:
        - asset: assets/fonts/pressstart.ttf