name: graphx
description: Render API on top of CustomPainter to power-up your Flutter apps to the next level.
version: 0.9.9
homepage: https://github.com/roipeker/graphx

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  xml: ^5.0.0-nullsafety.1
  http: ^0.13.0-nullsafety.0
  flutter_svg: ^0.21.0-nullsafety.0

dev_dependencies:
  flutter_test:
    sdk: flutter
