name: graphx
description: Render API on top of CustomPainter to power-up your Flutter apps to the next level.
version: 0.9.5
homepage: https://github.com/roipeker/graphx

environment:
  sdk: ">=2.9.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  xml: ^4.5.1
  vector_math: ^2.0.8

dev_dependencies:
  pedantic: ^1.9.0
  flutter_test:
    sdk: flutter
  effective_dart: ^1.0.0
