name: graphx
description: Render API on top of CustomPainter to power-up your Flutter apps to the next level.
version: 1.0.13
homepage: https://github.com/roipeker/graphx

environment:
  sdk: ">=2.19.0 <4.0.0"
  flutter: ">=2.1.0"

dependencies:
  flutter:
    sdk: flutter
  xml: ^6.2.2
  http: ^1.1.0
  flutter_svg: ^1.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1